#ifndef IntCtrl_Types_H
#define IntCtrl_Types_H

#define GPIO_Port_A               0
#define GPIO_Port_B               1
#define GPIO_Port_C               2
#define GPIO_Port_D               3
#define GPIO_Port_E               4
#define UART0                     5
#define UART1                     6
#define SSI0                      7
#define I2C0                      8 
#define PWM0_Fault                9
#define PWM0_Generator_0          10
#define PWM0_Generator_1          11 
#define PWM0_Generator_2          12
#define QEI0                      13
#define ADC0_Sequence_0           14
#define ADC0_Sequence_1           15
#define ADC0_Sequence_2           16
#define ADC0_Sequence_3           17
#define Watchdog_Timers_0         18
#define Timer_0A                  19          
#define Timer_0B                  20
#define Timer_1A                  21
#define Timer_1B                  22
#define Timer_2A                  23
#define Timer_2B                  24
#define Analog_Comparator_0       25
#define Analog_Comparator_1       26
#define System_Control            27
#define Flash_Memory_Control      28
#define GPIO_Port_F               29
#define UART2                     30
#define SSI1                      31
#define Timer_3A                  32
#define Timer_3B                  33
#define I2C1                      34
#define QEI1                      35
#define CAN0                      36
#define CAN1                      37
#define Hibernation_Module        38
#define USB                       39
#define PWM_Generator_3           40
#define ADC1_Sequence_3           46
#define SSI2                      47
#define SSI3                      48
#define UART3                     49
#define UART4                     50
#define UART5                     51
#define UART6                     52
#define UART7                     53
#define I2C2                      54
#define I2C3                      55
#define Timer_4A                  56
#define Timer_4B                  57
#define Timer_5A                  58
#define Timer_5B                  59
#define Timer0A                  60
#define Timer0B                  61
#define Timer1A                  62
#define Timer1B                  63
#define Timer2A                  64
#define Timer2B                  65
#define Timer3A                  66
#define Timer3B                  67
#define Timer4A                  68
#define Timer4B                  69
#define Timer5A                  70
#define Timer5B                  71
#define PWM1_Generator_0          72
#define PWM1_Generator_1          73
#define PWM1_Generator_2          74
#define PWM1_Generator_3          75
#define PWM1_Fault                76


#endif
